### ISSUE TITLE
Directon X - diagonal Branch is not implemented

### ISSUE THREAD

**Issue by ChristiaanLock** [BrianMacIntosh/SnakeEx#2]
In the SnakeEx specs direction X is defined as '[A] Diagonal branch. Same as '+' but on the diagonals and not the orthogonals.'.

However this direction seems not to be implemented.
For example:
input:
`X..
XX.
X.X`

Works (two matches expected):
`main:<*>X<F>X<F>X`

Fails (one match expected):
`main:<X>X<F>X<F>X`

Error:
(ln 1, col 7) expected '>', got 'X'.
(ln 1, col 8) expected newline, got '>'.

**Comment by BrianMacIntosh** [comment]
Fixed and deployed, thank you!
